const apexStandingsData = {
  // Apex Legends Standings Data
  "PROLEAGUE": [
    {
      
      team: "Falcons",
      TotalPoints: 120,
      "Round 1: A vs C": 0,
      "Round 1: A vs B": 0,
      "Round 1: B vs C": 8,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 7,
      "Round 2: B vs C": 9,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "100 Thieves",
      TotalPoints: 115,
      "Round 1: A vs C": 0,
      "Round 1: A vs B": 5,
      "Round 1: B vs C": 8,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 7,
      "Round 2: B vs C": 9,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "Twisted Minds",
      TotalPoints: 90,
      "Round 1: A vs C": 0,
      "Round 1: A vs B": 5,
      "Round 1: B vs C": 8,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 7,
      "Round 2: B vs C": 9,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "TSM",
      TotalPoints: 105,
      "Round 1: A vs C": 9,
      "Round 1: A vs B": 7,
      "Round 1: B vs C": 6,
      "Round 2: A vs B": 8,
      "Round 2: A vs C": 5,
      "Round 2: B vs C": 7,
      "Round 3: A vs B": 3,
      "Round 3: A vs C": 2,
      "Round 3: B vs C": 4,
    },
    {
      
      team: "Shopify Rebellion",
      TotalPoints: 100,
      "Round 1: A vs C": 8,
      "Round 1: A vs B": 6,
      "Round 1: B vs C": 7,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 9,
      "Round 2: B vs C": 6,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 5,
      "Round 3: B vs C": 3,
    },
    {
      
      team: "NRG",
      TotalPoints: 95,
      "Round 1: A vs C": 7,
      "Round 1: A vs B": 8,
      "Round 1: B vs C": 5,
      "Round 2: A vs B": 7,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 8,
      "Round 3: A vs B": 3,
      "Round 3: A vs C": 4,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "ROC Esports",
      TotalPoints: 90,
      "Round 1: A vs C": 6,
      "Round 1: A vs B": 5,
      "Round 1: B vs C": 7,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 8,
      "Round 2: B vs C": 5,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "Virtus.pro",
      TotalPoints: 85,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 6,
      "Round 1: B vs C": 8,
      "Round 2: A vs B": 7,
      "Round 2: A vs C": 5,
      "Round 2: B vs C": 6,
      "Round 3: A vs B": 3,
      "Round 3: A vs C": 4,
      "Round 3: B vs C": 5,
    },
    {
      team: "Envy",
      TotalPoints: 80,
      "Round 1: A vs C": 4,
      "Round 1: A vs B": 7,
      "Round 1: B vs C": 6,
      "Round 2: A vs B": 8,
      "Round 2: A vs C": 4,
      "Round 2: B vs C": 7,
      "Round 3: A vs B": 5,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 4,
    },
    {
      team: "KOI",
      TotalPoints: 75,
      "Round 1: A vs C": 3,
      "Round 1: A vs B": 5,
      "Round 1: B vs C": 7,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 3,
      "Round 2: B vs C": 8,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 2,
      "Round 3: B vs C": 5,
    },
    {
      team: "Ape Gang",
      TotalPoints: 70,
      "Round 1: A vs C": 2,
      "Round 1: A vs B": 6,
      "Round 1: B vs C": 5,
      "Round 2: A vs B": 7,
      "Round 2: A vs C": 4,
      "Round 2: B vs C": 6,
      "Round 3: A vs B": 3,
      "Round 3: A vs C": 5,
      "Round 3: B vs C": 4,
    },
    {
      team: "FUSION",
      TotalPoints: 65,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 6,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 7,
      "Round 2: B vs C": 5,
      "Round 3: A vs B": 6,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 4,
    },
    {
      team: "Team Liquid",
      TotalPoints: 60,
      "Round 1: A vs C": 6,
      "Round 1: A vs B": 7,
      "Round 1: B vs C": 5,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 8,
      "Round 2: B vs C": 4,
      "Round 3: A vs B": 5,
      "Round 3: A vs C": 4,
      "Round 3: B vs C": 3,
    },
    {
      team: "Sentinels",
      TotalPoints: 55,
      "Round 1: A vs C": 7,
      "Round 1: A vs B": 6,
      "Round 1: B vs C": 7,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 5,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      team: "Ninjas in Pyjamas",
      TotalPoints: 50,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 6,
      "Round 2: A vs B": 7,
      "Round 2: A vs C": 5,
      "Round 2: B vs C": 7,
      "Round 3: A vs B": 6,
      "Round 3: A vs C": 4,
      "Round 3: B vs C": 3,
    },
    {
      team: "bored",
      TotalPoints: 45,
      "Round 1: A vs C": 4,
      "Round 1: A vs B": 3,
      "Round 1: B vs C": 5,
      "Round 2: A vs B": 4,
      "Round 2: A vs C": 3,
      "Round 2: B vs C": 6,
      "Round 3: A vs B": 5,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      team: "CIMJ MX",
      TotalPoints: 40,
      "Round 1: A vs C": 3,
      "Round 1: A vs B": 5,
      "Round 1: B vs C": 4,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 4,
      "Round 2: B vs C": 5,
      "Round 3: A vs B": 3,
      "Round 3: A vs C": 2,
      "Round 3: B vs C": 4,
    },
    {
      team: "Flat",
      TotalPoints: 35,
      "Round 1: A vs C": 6,
      "Round 1: A vs B": 7,
      "Round 1: B vs C": 5,
      "Round 2: A vs B": 6,
      "Round 2: A vs C": 5,
      "Round 2: B vs C": 4,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 5,
    },
    {
    
      team: "Team S",
      TotalPoints: 30,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 3,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 3,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "Team S",
      TotalPoints: 30,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 3,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 3,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "Team S",
      TotalPoints: 30,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 3,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 3,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      
      team: "Team S",
      TotalPoints: 30,
      "Round 1: A vs C": 5,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 3,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 3,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
    {
      team: "CTE",
      TotalPoints: 130,
      "Round 1: A vs C": 130,
      "Round 1: A vs B": 4,
      "Round 1: B vs C": 3,
      "Round 2: A vs B": 5,
      "Round 2: A vs C": 6,
      "Round 2: B vs C": 3,
      "Round 3: A vs B": 4,
      "Round 3: A vs C": 3,
      "Round 3: B vs C": 2,
    },
  ],
};

const valorantStandingsData = {
  // Valorant Standings Data
  "CHAMPIONSHIP": [
    {
      rank: 1,
      team: "Team X",
      TotalPoints: 150,
      "Match 1": 3,
      "Match 2": 2,
      "Match 3": 4,
    },
    {
      rank: 2,
      team: "Team Y",
      TotalPoints: 140,
      "Match 1": 2,
      "Match 2": 3,
      "Match 3": 5,
    },
    {
      rank: 3,
      team: "Team Z",
      TotalPoints: 130,
      "Match 1": 4,
      "Match 2": 1,
      "Match 3": 3,
    },
    
  ],
};

export default apexStandingsData;
